In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os

data_path = "../data/raw"

os.listdir(data_path)

['nba.sqlite', 'synthetic_basketball_dataset.csv']

In [2]:
import sqlite3

csv_path = "../data/raw/synthetic_basketball_dataset.csv"
sqlite_path = "../data/raw/nba.sqlite"

df = pd.read_csv(csv_path)

df.head()

,Match_ID,A_Off_Rating,A_Def_Rating,A_Net_Rating,A_Star_Player,A_Chemistry,A_Injury,A_Last5_WinPct,A_Momentum,A_Rest,...,B_Net_Rating,B_Star_Player,B_Chemistry,B_Injury,B_Last5_WinPct,B_Momentum,B_Rest,Home_Team,Tournament_Stage,Winner
0,0,113.973713,106.893886,7.079828,94.448975,0.899518,0.108755,0.593526,0.624098,3,...,-5.002731,76.325219,0.576689,0.363810,0.385038,0.382014,2,B,2,1
1,1,112.844411,111.336089,1.508322,87.113290,0.696632,0.139330,0.403514,0.457163,1,...,11.006888,101.985961,0.806116,0.084199,0.759965,0.756135,3,B,1,0
2,2,92.573326,99.648829,-7.075503,78.116044,0.514936,0.196338,0.139161,0.215553,2,...,0.787960,76.999023,0.618309,0.167988,0.357807,0.422560,2,B,0,0
3,3,115.422139,113.587522,1.834617,88.957537,0.753169,0.074773,0.547052,0.546526,2,...,-1.909460,81.294785,0.537236,0.369147,0.330580,0.379311,0,B,2,1
4,4,106.810893,107.513087,-0.702194,88.464371,0.532514,0.078207,0.645234,0.580122,0,...,-17.689937,58.560097,0.096696,0.174742,0.106837,0.122369,0,B,0,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Match_ID          10000 non-null  int64
 1   A_Off_Rating      10000 non-null  float64
 2   A_Def_Rating      10000 non-null  float64
 3   A_Net_Rating      10000 non-null  float64
 4   A_Star_Player     10000 non-null  float64
 5   A_Chemistry       10000 non-null  float64
 6   A_Injury          10000 non-null  float64
 7   A_Last5_WinPct    10000 non-null  float64
 8   A_Momentum        10000 non-null  float64
 9   A_Rest            10000 non-null  int64
 10  B_Off_Rating      10000 non-null  float64
 11  B_Def_Rating      10000 non-null  float64
 12  B_Net_Rating      10000 non-null  float64
 13  B_Star_Player     10000 non-null  float64
 14  B_Chemistry       10000 non-null  float64
 15  B_Injury          10000 non-null  float64
 16  B_Last5_WinPct    10000 non-null  float64
 17  B_Momentum        10000 non-null  float64
 18  B_Rest            10000 non-null  int64
 19  Home_Team         10000 non-null  str
 20  Tournament_Stage  10000 non-null  int64
 21  Winner            10000 non-null  int64
dtypes: float64(16), int64(5), str(1)
memory usage: 1.7 MB

In [4]:
df.describe()

,Match_ID,A_Off_Rating,A_Def_Rating,A_Net_Rating,A_Star_Player,A_Chemistry,A_Injury,A_Last5_WinPct,A_Momentum,A_Rest,...,B_Def_Rating,B_Net_Rating,B_Star_Player,B_Chemistry,B_Injury,B_Last5_WinPct,B_Momentum,B_Rest,Tournament_Stage,Winner
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4999.50000,109.959151,108.055078,1.904073,87.820217,0.630887,0.200446,0.542669,0.540651,1.996700,...,108.063886,1.842357,87.768063,0.629491,0.199870,0.539582,0.538319,2.008100,1.006400,0.486200
std,2886.89568,8.075518,7.935120,11.210028,17.428310,0.228214,0.120457,0.267110,0.246211,1.407298,...,7.913181,11.250343,17.608610,0.229502,0.120064,0.269856,0.248353,1.410544,0.820138,0.499835
min,0.00000,79.928701,80.039638,-38.638085,26.614871,0.000000,0.001405,0.003189,0.012642,0.000000,...,78.537735,-40.434007,16.477816,0.000000,0.001201,0.002858,0.008609,0.000000,0.000000,0.000000
25%,2499.75000,104.440767,102.804890,-5.603891,76.271680,0.475520,0.108076,0.321643,0.344167,1.000000,...,102.678203,-5.675688,75.974295,0.473311,0.108369,0.311486,0.334747,1.000000,0.000000,0.000000
50%,4999.50000,109.924417,108.030776,1.732141,87.491160,0.634584,0.179836,0.556707,0.548606,2.000000,...,108.143735,1.714221,87.741442,0.633936,0.178744,0.552723,0.548806,2.000000,1.000000,0.000000
75%,7499.25000,115.351702,113.448176,9.436585,99.552498,0.803179,0.271872,0.769752,0.746068,3.000000,...,113.390110,9.434904,99.569379,0.800963,0.271432,0.777201,0.752030,3.000000,2.000000,1.000000
max,9999.00000,140.706261,139.328613,43.151995,154.082999,1.000000,0.771128,0.996552,0.992571,4.000000,...,133.287564,50.255645,160.369555,1.000000,0.756458,0.997995,0.996187,4.000000,2.000000,1.000000

In [5]:
conn = sqlite3.connect(sqlite_path)

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

tables

                   name
0                  game
1          game_summary
2           other_stats
3             officials
4      inactive_players
5             game_info
6            line_score
7          play_by_play
8                player
9                  team
10   common_player_info
11         team_details
12         team_history
13  draft_combine_stats
14        draft_history
15     team_info_common